// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJnN47YuQ7Crf6CgtkUrOr49H1pjUgkqU',
    appId: '1:40330122359:web:97875ef22bbddc02cb6272',
    messagingSenderId: '40330122359',
    projectId: 'noteapp-2a574',
    authDomain: 'noteapp-2a574.firebaseapp.com',
    storageBucket: 'noteapp-2a574.firebasestorage.app',
    measurementId: 'G-VM1PTBBGN6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsEeLWxvdR1bH70HS_2TlxWMSE7szYPg4',
    appId: '1:40330122359:android:5171f08ce99c7a33cb6272',
    messagingSenderId: '40330122359',
    projectId: 'noteapp-2a574',
    storageBucket: 'noteapp-2a574.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCr67pf1kcKyzybNCIo3sLjauUewTUpXjg',
    appId: '1:40330122359:ios:04847a69cd89456bcb6272',
    messagingSenderId: '40330122359',
    projectId: 'noteapp-2a574',
    storageBucket: 'noteapp-2a574.firebasestorage.app',
    iosBundleId: 'com.example.noteApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCr67pf1kcKyzybNCIo3sLjauUewTUpXjg',
    appId: '1:40330122359:ios:04847a69cd89456bcb6272',
    messagingSenderId: '40330122359',
    projectId: 'noteapp-2a574',
    storageBucket: 'noteapp-2a574.firebasestorage.app',
    iosBundleId: 'com.example.noteApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJnN47YuQ7Crf6CgtkUrOr49H1pjUgkqU',
    appId: '1:40330122359:web:3d8b4a56af79276ecb6272',
    messagingSenderId: '40330122359',
    projectId: 'noteapp-2a574',
    authDomain: 'noteapp-2a574.firebaseapp.com',
    storageBucket: 'noteapp-2a574.firebasestorage.app',
    measurementId: 'G-6Q9VFSWG3J',
  );
}
